
services:


  mongo:
    image: mongo:latest
    container_name: mongo-pokemon
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: pokemon-api
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
      - ./pokemon/api/scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    container_name: api-pokemon
    restart: on-failure
    env_file:
      - ./api/.env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
    
